pretest:
  pipeline: jccormier/sample-assets/.github/workflows/stage.yaml@main

test:
  pipeline: jccormier/sample-assets/.github/workflows/test.yml@main

posttest:
  pipeline: jccormier/sample-assets/.github/workflows/promote.yaml@main
