workflows:
  pre-test:
    path: jccormier/sample-assets/.github/workflows/stage.yaml@main

  test:
    path: jccormier/sample-assets/.github/workflows/test.yml@main

  post-test:
    path: jccormier/sample-assets/.github/workflows/promote.yaml@main
