name: 'Trigger deployment to staging'
run-name: Staging ${{ inputs.UUID }}

on:
  workflow_dispatch:
    inputs:
      UUID:
        description: 'Distinct ID'
        required: false
        
jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Mock staging deployment
        run: |
          echo "Mock staging deployment executing..."
            
