name: 'Trigger deployment to staging'
run-name: ${{ inputs.run_name }}

on:
  workflow_dispatch:
    inputs:
      run_name:
        description: 'Workflow Run Name'
        required: false
        
jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Mock staging deployment
        run: |
          echo "Mock staging deployment executing..."
            
