name: 'Trigger Test Execution'

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test Suite'
        required: true

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Mock test run
        run: |
          echo "Mock test run executing ... ${{ github.event.inputs.test_suite }}"
            
