name: 'Trigger tests execution'
run-name: Testing ${{ inputs.UUID }}

on:
  workflow_dispatch:
    inputs:
      UUID:
        description: 'Distinct ID'
        required: false

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Mock test run
        run: |
          echo "Mock test run executing..."
            
