name: 'Trigger Test Execution'

on:
  workflow_dispatch:

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      actions: write
    steps:
      - name: Test Run
        run: |
          echo "Mock test run executing ... Smoke Tests" > test_results.txt    
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_results.txt
          retention-days: 5
