name: 'Trigger tests execution'
run-name: ${{ inputs.run_name }}

on:
  workflow_dispatch:
    inputs:
      run_name:
        description: 'Workflow Run Name'
        required: false

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Mock test run
        run: |
          echo "Mock test run executing..."
          exit 1
            
